import React, {useEffect, useMemo, useState} from 'react';
import {LayoutDashboard, Users, Stethoscope, CalendarDays, Receipt, Pill, FlaskConical, BedDouble, Search, Bell, LogOut, Menu, X, Plus, Trash2, Edit3, CheckCircle2, Clock3, AlertCircle, Activity, HeartPulse, ChevronRight} from 'lucide-react';
import {BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line} from 'recharts';

const patients0=[
{id:'P-1001',name:'Aarav Sharma',age:32,gender:'Male',phone:'98765 43210',condition:'Fever',status:'Active'},
{id:'P-1002',name:'Priya Verma',age:27,gender:'Female',phone:'98111 22334',condition:'Migraine',status:'Active'},
{id:'P-1003',name:'Rahul Gupta',age:54,gender:'Male',phone:'98999 11223',condition:'Diabetes',status:'Follow-up'},
{id:'P-1004',name:'Ananya Singh',age:41,gender:'Female',phone:'97666 44556',condition:'Hypertension',status:'Active'},
{id:'P-1005',name:'Vikram Mehta',age:63,gender:'Male',phone:'98888 77665',condition:'Cardiac',status:'Critical'}];
const doctors0=[
{id:'D-101',name:'Dr. Neha Kapoor',spec:'Cardiologist',dept:'Cardiology',exp:'12 years',status:'Available'},
{id:'D-102',name:'Dr. Arjun Malhotra',spec:'Neurologist',dept:'Neurology',exp:'9 years',status:'In Surgery'},
{id:'D-103',name:'Dr. Simran Kaur',spec:'Pediatrician',dept:'Pediatrics',exp:'7 years',status:'Available'},
{id:'D-104',name:'Dr. Rohan Bhatia',spec:'Orthopedic',dept:'Orthopedics',exp:'11 years',status:'Available'}];
const meds0=[
{id:'MED-001',name:'Paracetamol 500mg',stock:245,expiry:'15 Sep 2027',status:'In Stock'},
{id:'MED-002',name:'Amoxicillin 250mg',stock:82,expiry:'20 Jan 2027',status:'In Stock'},
{id:'MED-003',name:'Insulin Glargine',stock:12,expiry:'02 Sep 2026',status:'Low Stock'},
{id:'MED-004',name:'Azithromycin 500mg',stock:0,expiry:'11 Dec 2026',status:'Out of Stock'},
{id:'MED-005',name:'Cetirizine 10mg',stock:190,expiry:'07 Mar 2028',status:'In Stock'}];
const appointments0=[
{id:'APT-501',patient:'Aarav Sharma',doctor:'Dr. Neha Kapoor',date:'30 Aug 2026',time:'10:00 AM',type:'Consultation',status:'Confirmed'},
{id:'APT-502',patient:'Priya Verma',doctor:'Dr. Arjun Malhotra',date:'30 Aug 2026',time:'11:30 AM',type:'Follow-up',status:'Pending'},
{id:'APT-503',patient:'Rahul Gupta',doctor:'Dr. Rohan Bhatia',date:'31 Aug 2026',time:'09:30 AM',type:'Check-up',status:'Confirmed'}];
const bills0=[
{id:'INV-9001',patient:'Aarav Sharma',service:'Consultation',amount:'₹2,500',date:'30 Aug 2026',status:'Paid'},
{id:'INV-9002',patient:'Priya Verma',service:'MRI Scan',amount:'₹6,800',date:'30 Aug 2026',status:'Pending'},
{id:'INV-9003',patient:'Rahul Gupta',service:'Room + Medicines',amount:'₹18,400',date:'29 Aug 2026',status:'Paid'}];
const labs0=[
{id:'LAB-301',patient:'Aarav Sharma',test:'CBC',date:'30 Aug 2026',status:'Completed'},
{id:'LAB-302',patient:'Priya Verma',test:'MRI Brain',date:'30 Aug 2026',status:'Processing'},
{id:'LAB-303',patient:'Rahul Gupta',test:'HbA1c',date:'29 Aug 2026',status:'Completed'}];
const rooms0=[
{id:'101',type:'General Ward',status:'Available',price:'₹1,500',patient:''},
{id:'102',type:'General Ward',status:'Occupied',price:'₹1,500',patient:'Aarav Sharma'},
{id:'201',type:'Private',status:'Available',price:'₹4,000',patient:''},
{id:'202',type:'Private',status:'Occupied',price:'₹4,000',patient:'Priya Verma'},
{id:'301',type:'ICU',status:'Occupied',price:'₹8,500',patient:'Vikram Mehta'},
{id:'302',type:'ICU',status:'Available',price:'₹8,500',patient:''}];

function useStore(key, initial){const [v,setV]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))||initial}catch{return initial}});useEffect(()=>localStorage.setItem(key,JSON.stringify(v)),[key,v]);return [v,setV]}
function Badge({children,type=''}){return <span className={'badge '+String(type).toLowerCase().replaceAll(' ','-')}>{children}</span>}
function PageTitle({title,sub,action,onAction}){return <div className="page-title"><div><h1>{title}</h1><p>{sub}</p></div>{action&&<button className="primary" onClick={onAction}><Plus size={17}/>{action}</button>}</div>}
function Modal({title,onClose,children}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={onClose}><X size={19}/></button></div>{children}</div></div>}
function Form({fields,onSave,onClose}){const [data,setData]=useState(Object.fromEntries(fields.map(f=>[f.name,f.value??''])));const change=(e)=>setData({...data,[e.target.name]:e.target.value});return <form onSubmit={e=>{e.preventDefault();onSave(data)}}><div className="form-grid">{fields.map(f=><label key={f.name}>{f.label}<input name={f.name} type={f.type||'text'} required={f.required!==false} value={data[f.name]} onChange={change}/></label>)}</div><div className="modal-actions"><button type="button" className="outline" onClick={onClose}>Cancel</button><button className="primary">Save</button></div></form>}

function Dashboard({setPage,patients}){const revenue=[{m:'Jan',v:42},{m:'Feb',v:48},{m:'Mar',v:55},{m:'Apr',v:51},{m:'May',v:67},{m:'Jun',v:72},{m:'Jul',v:78},{m:'Aug',v:84}];const weekly=[{d:'Mon',v:42},{d:'Tue',v:58},{d:'Wed',v:51},{d:'Thu',v:70},{d:'Fri',v:64},{d:'Sat',v:82},{d:'Sun',v:55}];return <><PageTitle title="Dashboard" sub="Welcome back, Admin. Here's today's hospital overview."/><div className="stats">{[['Total Patients',patients.length,'patients',Users],['Doctors',4,'doctors',Stethoscope],['Appointments',3,'appointments',CalendarDays],['Revenue','₹8.42L','revenue',Receipt]].map(([a,b,k,I])=><div className="stat" key={a}><div className="stat-top"><span>{a}</span><div className="icon"><I size={19}/></div></div><strong>{b}</strong><small className="growth">+12.5% <span>vs last month</span></small></div>)}</div><div className="grid-2"><div className="card"><div className="card-head"><div><h3>Revenue Overview</h3><p>Monthly revenue in ₹ lakh</p></div></div><div className="chart"><ResponsiveContainer width="100%" height={260}><BarChart data={revenue}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="m"/><YAxis/><Tooltip/><Bar dataKey="v" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div><div className="card"><div className="card-head"><div><h3>Weekly Appointments</h3><p>Appointments this week</p></div><Activity size={20}/></div><div className="chart"><ResponsiveContainer width="100%" height={260}><LineChart data={weekly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="d"/><YAxis/><Tooltip/><Line type="monotone" dataKey="v" strokeWidth={3} dot={{r:4}}/></LineChart></ResponsiveContainer></div></div></div><div className="card lower"><div className="card-head"><h3>Quick Actions</h3></div><div className="quick-actions"><button onClick={()=>setPage('Patients')}><Users/>Manage Patients</button><button onClick={()=>setPage('Pharmacy')}><Pill/>Manage Pharmacy</button><button onClick={()=>setPage('Rooms & IPD')}><BedDouble/>Manage Rooms</button><button onClick={()=>setPage('Appointments')}><CalendarDays/>Appointments</button></div></div></>}

function Patients({patients,setPatients}){const [q,setQ]=useState('');const [modal,setModal]=useState(false);const [edit,setEdit]=useState(null);const filtered=patients.filter(p=>(p.name+p.id+p.condition+p.phone).toLowerCase().includes(q.toLowerCase()));const save=d=>{const p={...d,age:Number(d.age),id:edit?.id||'P-'+String(Date.now()).slice(-6),status:d.status||'Active'};setPatients(edit?patients.map(x=>x.id===edit.id?p:x):[...patients,p]);setModal(false);setEdit(null)};return <><PageTitle title="Patients" sub="Manage patient records and medical information." action="Add Patient" onAction={()=>{setEdit(null);setModal(true)}}/><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search patients..." value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="card table-wrap"><table><thead><tr><th>Patient</th><th>ID</th><th>Age / Gender</th><th>Phone</th><th>Condition</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><div className="person"><div className="avatar">{p.name.split(' ').map(x=>x[0]).join('')}</div><b>{p.name}</b></div></td><td>{p.id}</td><td>{p.age} / {p.gender}</td><td>{p.phone}</td><td>{p.condition}</td><td><Badge type={p.status}>{p.status}</Badge></td><td className="actions"><button onClick={()=>{setEdit(p);setModal(true)}} title="Edit"><Edit3 size={16}/></button><button onClick={()=>confirm('Delete this patient?')&&setPatients(patients.filter(x=>x.id!==p.id))} title="Delete"><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>{modal&&<Modal title={edit?'Edit Patient':'Add Patient'} onClose={()=>{setModal(false);setEdit(null)}}><Form onSave={save} onClose={()=>setModal(false)} fields={[{name:'name',label:'Full Name',value:edit?.name},{name:'age',label:'Age',type:'number',value:edit?.age},{name:'gender',label:'Gender',value:edit?.gender||'Female'},{name:'phone',label:'Phone',value:edit?.phone},{name:'condition',label:'Condition',value:edit?.condition},{name:'status',label:'Status',value:edit?.status||'Active'}]}/></Modal>}</>}

function Doctors(){const [doctors,setDoctors]=useStore('hms_doctors',doctors0);const [modal,setModal]=useState(false);const save=d=>{setDoctors([...doctors,{...d,id:'D-'+Date.now().toString().slice(-4)}]);setModal(false)};return <><PageTitle title="Doctors" sub="View doctors, departments and availability." action="Add Doctor" onAction={()=>setModal(true)}/><div className="doctor-grid">{doctors.map(d=><div className="card doctor" key={d.id}><div className="doctor-top"><div className="doc-avatar"><Stethoscope size={25}/></div><Badge type={d.status}>{d.status}</Badge></div><h3>{d.name}</h3><p>{d.spec}</p><div className="doctor-meta"><span>{d.dept}</span><span>{d.exp}</span></div><button className="outline" onClick={()=>confirm('Remove this doctor?')&&setDoctors(doctors.filter(x=>x.id!==d.id))}>Remove Doctor</button></div>)}</div>{modal&&<Modal title="Add Doctor" onClose={()=>setModal(false)}><Form onSave={save} onClose={()=>setModal(false)} fields={[{name:'name',label:'Doctor Name'},{name:'spec',label:'Specialization'},{name:'dept',label:'Department'},{name:'exp',label:'Experience',value:'5 years'},{name:'status',label:'Status',value:'Available'}]}/></Modal>}</>}

function Appointments(){const [items,setItems]=useStore('hms_appointments',appointments0);const [modal,setModal]=useState(false);const save=d=>{setItems([...items,{...d,id:'APT-'+Date.now().toString().slice(-4),status:'Pending'}]);setModal(false)};return <><PageTitle title="Appointments" sub="Schedule and manage patient appointments." action="Book Appointment" onAction={()=>setModal(true)}/><div className="stats mini">{[['Today',items.length,CalendarDays],['Confirmed',items.filter(x=>x.status==='Confirmed').length,CheckCircle2],['Pending',items.filter(x=>x.status==='Pending').length,Clock3],['Cancelled',items.filter(x=>x.status==='Cancelled').length,AlertCircle]].map(([x,y,I])=><div className="stat" key={x}><div className="stat-top"><span>{x}</span><div className="icon"><I size={18}/></div></div><strong>{y}</strong></div>)}</div><div className="card table-wrap"><table><thead><tr><th>ID</th><th>Patient</th><th>Doctor</th><th>Date & Time</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(a=><tr key={a.id}><td><b>{a.id}</b></td><td>{a.patient}</td><td>{a.doctor}</td><td>{a.date}<br/><span className="muted">{a.time}</span></td><td>{a.type}</td><td><Badge type={a.status}>{a.status}</Badge></td><td><button className="text-btn" onClick={()=>setItems(items.map(x=>x.id===a.id?{...x,status:x.status==='Cancelled'?'Pending':'Cancelled'}:x))}>{a.status==='Cancelled'?'Restore':'Cancel'}</button></td></tr>)}</tbody></table></div>{modal&&<Modal title="Book Appointment" onClose={()=>setModal(false)}><Form onSave={save} onClose={()=>setModal(false)} fields={[{name:'patient',label:'Patient Name'},{name:'doctor',label:'Doctor Name'},{name:'date',label:'Date'},{name:'time',label:'Time'},{name:'type',label:'Appointment Type',value:'Consultation'}]}/></Modal>}</>}

function Billing(){const [bills,setBills]=useStore('hms_bills',bills0);const [modal,setModal]=useState(false);const save=d=>{setBills([...bills,{...d,id:'INV-'+Date.now().toString().slice(-4),date:'30 Aug 2026',status:'Pending'}]);setModal(false)};return <><PageTitle title="Billing & Payments" sub="Manage invoices, payments and hospital charges." action="Create Invoice" onAction={()=>setModal(true)}/><div className="stats"><div className="stat"><span>Total Revenue</span><strong>₹8.42L</strong></div><div className="stat"><span>Paid</span><strong>₹7.18L</strong></div><div className="stat"><span>Pending</span><strong>₹94,500</strong></div><div className="stat"><span>Invoices</span><strong>{bills.length}</strong></div></div><div className="card table-wrap"><table><thead><tr><th>Invoice</th><th>Patient</th><th>Service</th><th>Amount</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{bills.map(r=><tr key={r.id}><td><b>{r.id}</b></td><td>{r.patient}</td><td>{r.service}</td><td>{r.amount}</td><td>{r.date}</td><td><Badge type={r.status}>{r.status}</Badge></td><td><button className="text-btn" onClick={()=>setBills(bills.map(x=>x.id===r.id?{...x,status:x.status==='Paid'?'Pending':'Paid'}:x))}>{r.status==='Paid'?'Mark Pending':'Mark Paid'}</button></td></tr>)}</tbody></table></div>{modal&&<Modal title="Create Invoice" onClose={()=>setModal(false)}><Form onSave={save} onClose={()=>setModal(false)} fields={[{name:'patient',label:'Patient Name'},{name:'service',label:'Service'},{name:'amount',label:'Amount',value:'₹0'}]}/></Modal>}</>}

function Pharmacy(){const [meds,setMeds]=useStore('hms_meds',meds0);const [q,setQ]=useState('');const [modal,setModal]=useState(false);const [edit,setEdit]=useState(null);const save=d=>{const stock=Number(d.stock);const m={...d,stock,status:stock===0?'Out of Stock':stock<20?'Low Stock':'In Stock',id:edit?.id||'MED-'+Date.now().toString().slice(-4)};setMeds(edit?meds.map(x=>x.id===edit.id?m:x):[...meds,m]);setModal(false);setEdit(null)};const list=meds.filter(m=>m.name.toLowerCase().includes(q.toLowerCase()));return <><PageTitle title="Pharmacy" sub="Track medicines, inventory and stock levels." action="Add Medicine" onAction={()=>{setEdit(null);setModal(true)}}/><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search medicine..." value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="card table-wrap"><table><thead><tr><th>Medicine</th><th>Code</th><th>Stock</th><th>Expiry</th><th>Status</th><th>Actions</th></tr></thead><tbody>{list.map(m=><tr key={m.id}><td><b>{m.name}</b></td><td>{m.id}</td><td>{m.stock}</td><td>{m.expiry}</td><td><Badge type={m.status}>{m.status}</Badge></td><td className="actions"><button onClick={()=>{setEdit(m);setModal(true)}}><Edit3 size={16}/></button><button onClick={()=>confirm('Delete this medicine?')&&setMeds(meds.filter(x=>x.id!==m.id))}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>{modal&&<Modal title={edit?'Edit Medicine':'Add Medicine'} onClose={()=>{setModal(false);setEdit(null)}}><Form onSave={save} onClose={()=>setModal(false)} fields={[{name:'name',label:'Medicine Name',value:edit?.name},{name:'stock',label:'Stock Quantity',type:'number',value:edit?.stock||0},{name:'expiry',label:'Expiry Date',value:edit?.expiry}]}/></Modal>}</>}

function Laboratory(){const [labs,setLabs]=useStore('hms_labs',labs0);const [modal,setModal]=useState(false);const save=d=>{setLabs([...labs,{...d,id:'LAB-'+Date.now().toString().slice(-4),date:'30 Aug 2026',status:'Pending'}]);setModal(false)};return <><PageTitle title="Laboratory" sub="Manage diagnostic tests and patient reports." action="Order Test" onAction={()=>setModal(true)}/><div className="card table-wrap"><table><thead><tr><th>Test ID</th><th>Patient</th><th>Test</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{labs.map(t=><tr key={t.id}><td>{t.id}</td><td>{t.patient}</td><td><b>{t.test}</b></td><td>{t.date}</td><td><Badge type={t.status}>{t.status}</Badge></td><td><button className="text-btn" onClick={()=>setLabs(labs.map(x=>x.id===t.id?{...x,status:x.status==='Completed'?'Processing':'Completed'}:x))}>Update</button></td></tr>)}</tbody></table></div>{modal&&<Modal title="Order Laboratory Test" onClose={()=>setModal(false)}><Form onSave={save} onClose={()=>setModal(false)} fields={[{name:'patient',label:'Patient Name'},{name:'test',label:'Test Name'}]}/></Modal>}</>}

function Rooms(){const [rooms,setRooms]=useStore('hms_rooms',rooms0);const [modal,setModal]=useState(false);const available=rooms.filter(r=>r.status==='Available');const patients=['Aarav Sharma','Priya Verma','Rahul Gupta','Ananya Singh','Vikram Mehta'];const save=d=>{setRooms(rooms.map(r=>r.id===d.room?{...r,status:'Occupied',patient:d.patient}:r));setModal(false)};return <><PageTitle title="Rooms & IPD" sub="Monitor room availability, admissions and discharge." action="Admit Patient" onAction={()=>setModal(true)}/><div className="room-grid">{rooms.map(r=><div className={'room card '+r.status.toLowerCase()} key={r.id}><div className="room-icon"><BedDouble size={22}/></div><div><span>Room {r.id}</span><h3>{r.type}</h3><small>{r.price} / day</small>{r.patient&&<small className="room-patient">Patient: {r.patient}</small>}</div><div className="room-actions"><Badge type={r.status}>{r.status}</Badge>{r.status==='Occupied'&&<button className="text-btn" onClick={()=>setRooms(rooms.map(x=>x.id===r.id?{...x,status:'Available',patient:''}:x))}>Discharge</button>}</div></div>)}</div>{modal&&<Modal title="Admit Patient" onClose={()=>setModal(false)}><form onSubmit={e=>{e.preventDefault();save({room:e.target.room.value,patient:e.target.patient.value})}}><div className="form-grid"><label>Patient<select name="patient" required>{patients.map(p=><option key={p}>{p}</option>)}</select></label><label>Available Room<select name="room" required>{available.length?available.map(r=><option key={r.id} value={r.id}>Room {r.id} - {r.type}</option>):<option>No room available</option>}</select></label></div><div className="modal-actions"><button type="button" className="outline" onClick={()=>setModal(false)}>Cancel</button><button className="primary" disabled={!available.length}>Admit Patient</button></div></form></Modal>}</>}

function Login({onLogin}){return <div className="login"><div className="login-card"><div className="brand big"><div className="brand-mark"><HeartPulse size={25}/></div><div><b>MediCare</b><span>Hospital Management</span></div></div><h1>Welcome back</h1><p>Sign in to your hospital administration panel.</p><label>Email<input defaultValue="admin@hospital.com"/></label><label>Password<input type="password" defaultValue="admin123"/></label><button className="primary full" onClick={onLogin}>Sign In <ChevronRight size={18}/></button><small className="demo">Demo: admin@hospital.com / admin123</small></div></div>}

export default function App(){const [logged,setLogged]=useState(false);const [page,setPage]=useState('Dashboard');const [patients,setPatients]=useStore('hms_patients',patients0);const [open,setOpen]=useState(false);const nav=[['Dashboard',LayoutDashboard],['Patients',Users],['Doctors',Stethoscope],['Appointments',CalendarDays],['Billing',Receipt],['Pharmacy',Pill],['Laboratory',FlaskConical],['Rooms & IPD',BedDouble]];const content=useMemo(()=>({Dashboard:<Dashboard setPage={setPage} patients={patients}/>,Patients:<Patients patients={patients} setPatients={setPatients}/>,Doctors:<Doctors/>,Appointments:<Appointments/>,Billing:<Billing/>,Pharmacy:<Pharmacy/>,Laboratory:<Laboratory/>,['Rooms & IPD']:<Rooms/>})[page],[page,patients]);if(!logged)return <Login onLogin={()=>setLogged(true)}/>;return <div className="app"><aside className={open?'open':''}><div className="brand"><div className="brand-mark"><HeartPulse size={23}/></div><div><b>MediCare</b><span>Hospital Management</span></div><button className="close" onClick={()=>setOpen(false)}><X/></button></div><div className="nav">{nav.map(([n,I])=><button className={page===n?'active':''} key={n} onClick={()=>{setPage(n);setOpen(false)}}><I size={19}/><span>{n}</span></button>)}</div><div className="sidebar-bottom"><div className="admin"><div className="avatar">MA</div><div><b>Admin</b><span>Administrator</span></div></div><button className="logout" onClick={()=>setLogged(false)}><LogOut size={18}/>Logout</button></div></aside><main><header><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div className="header-search"><Search size={17}/><input placeholder="Search anything..."/></div><div className="header-right"><button className="bell"><Bell size={19}/><i/></button><div className="profile"><div className="avatar">MA</div><div><b>Mahak Admin</b><span>Administrator</span></div></div></div></header><section className="content">{content}</section></main></div>}
